name       = "forimage"
version    = "VERSION"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright (c) 2023, Seyed Ali Ghasemi"
license    = "LICENSE"

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false
module-naming    = false

[install]
library = false

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[[example]]
name       = "example1"
source-dir = "example"
main       = "example1.f90"

[[example]]
name       = "example2"
source-dir = "example"
main       = "example2.f90"

[[example]]
name       = "example3"
source-dir = "example"
main       = "example3.f90"

[[example]]
name       = "example4"
source-dir = "example"
main       = "example4.f90"

[[example]]
name       = "example5"
source-dir = "example"
main       = "example5.f90"

[[example]]
name       = "example6"
source-dir = "example"
main       = "example6.f90"

[[example]]
name       = "example7"
source-dir = "example"
main       = "example7.f90"

[[example]]
name       = "example8"
source-dir = "example"
main       = "example8.f90"

[[example]]
name       = "example9"
source-dir = "example"
main       = "example9.f90"

[[example]]
name       = "example10"
source-dir = "example"
main       = "example10.f90"

[[example]]
name       = "example11"
source-dir = "example"
main       = "example11.f90"

[[example]]
name       = "example12"
source-dir = "example"
main       = "example12.f90"