allocate_colors – ForImage
allocate_colors Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental subroutine allocate_colors(this)
Type Bound
format_lut
Arguments
Type Intent Optional Attributes Name
class(format_lut), intent(inout) :: this
Called by
Source Code
   pure elemental subroutine allocate_colors(this)
      class(format_lut), intent(inout) :: this
      if (allocated(this%colors)) deallocate(this%colors)
      allocate(this%colors(this%num_colors, this%dim_colors))
   end subroutine allocate_colors
Call graph
import calls allocate_colors
set calls allocate_colors
test15 calls set