allocate_pixels – ForImage
allocate_pixels Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private pure elemental subroutine allocate_pixels(this)
Allocates memory for the pixels of the PNM image.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
Called by
Source Code
   elemental pure subroutine allocate_pixels(this)
      class(format_pnm), intent(inout) :: this
      select case(this%magic_number)
       case('P1')
         if (.not.allocated(this%pixels)) allocate(this%pixels(this%height, this%width))
       case('P2')
         if (.not.allocated(this%pixels)) allocate(this%pixels(this%height, this%width))
       case('P3')
         if (.not.allocated(this%pixels)) allocate(this%pixels(this%height, 3*this%width))
       case('P4')
         if (.not.allocated(this%pixels)) allocate(this%pixels(this%height, this%width))
       case('P5')
         if (.not.allocated(this%pixels)) allocate(this%pixels(this%height, this%width))
       case('P6')
         if (.not.allocated(this%pixels)) allocate(this%pixels(this%height, 3*this%width))
      end select
   end subroutine allocate_pixels
Call graph
crop calls allocate_pixels
import_pnm calls allocate_pixels
resize calls allocate_pixels
rotate calls allocate_pixels
set_pnm calls allocate_pixels
save calls set_pnm
demo_ppm calls crop, import_pnm, resize, rotate, set_pnm
test calls set_pnm
test1 calls set_pnm
test10 calls import_pnm
test11 calls import_pnm
test12 calls import_pnm
test13 calls import_pnm
test14 calls import_pnm
test17 calls set_pnm
test18 calls set_pnm
test19 calls set_pnm
test2 calls set_pnm
test20 calls set_pnm
test21 calls set_pnm
test22 calls rotate, set_pnm
test23 calls set_pnm
test24 calls crop, set_pnm
test25 calls resize, set_pnm
test3 calls set_pnm
test4 calls set_pnm
test6 calls set_pnm
test7 calls import_pnm
test8 calls import_pnm
test9 calls import_pnm