aspect_ratio – ForImage
aspect_ratio Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental subroutine aspect_ratio(this, ratio)
Calculates the aspect ratio of the image. Required for print_info method.
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(in) :: this
real(kind=rk), intent(out) :: ratio
Called by
Source Code
   elemental pure subroutine aspect_ratio(this, ratio)
      class(format_pnm), intent(in) :: this
      real(rk), intent(out) :: ratio
      ratio = real(this%width, kind=rk) / real(this%height, kind=rk)
   end subroutine aspect_ratio
Call graph
print_info calls aspect_ratio
demo_ppm calls print_info
test calls print_info
test1 calls print_info
test10 calls print_info
test11 calls print_info
test12 calls print_info
test13 calls print_info
test14 calls print_info
test17 calls print_info
test18 calls print_info
test19 calls print_info
test2 calls print_info
test20 calls print_info
test21 calls print_info
test22 calls print_info
test23 calls print_info
test24 calls print_info
test25 calls print_info
test3 calls print_info
test4 calls print_info
test6 calls print_info
test7 calls print_info
test8 calls print_info
test9 calls print_info