brighten – ForImage
brighten Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
10 statements
Source File
private pure elemental subroutine brighten(this, factor)
Brightens or darkens the image. Only supported for PGM and PPM images.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
integer, intent(in) :: factor
Calls
Called by
Source Code
   elemental pure subroutine brighten(this, factor)
      class(format_pnm), intent(inout) :: this
      integer,           intent(in)    :: factor
      select case (this%file_format)
       case ('pbm')
         error stop 'brighten: This function is not supported for pbm files.'
       case ('pgm', 'ppm')
         call this%set_pixels(min(this%max_color, max(0, this%pixels + factor)))
      end select
   end subroutine brighten
Call graph
brighten calls set_pixels
set_pixel_a calls check_pixel_range
demo_ppm calls brighten
test18 calls brighten