check_pixel_range – ForImage
check_pixel_range Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
private pure subroutine check_pixel_range(this, pixels)
Checks if the pixel values are within the valid range.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
integer(kind=ik), intent(in), dimension(:,:) :: pixels
Called by
Source Code
   pure subroutine check_pixel_range(this, pixels)
      class(format_pnm),           intent(inout) :: this
      integer(ik), dimension(:,:), intent(in)    :: pixels
      ! Check if the pixel values are within the valid range
      select case (this%file_format)
       case ('pbm')
         if (maxval(pixels) > 1 .or. minval(pixels) < 0)&
         error stop 'set_pixels: Invalid pixel values. Valid values are 0 and 1.'
       case ('pgm')
         if (maxval(pixels) > this%max_color .or. minval(pixels) < 0)&
         error stop 'set_pixels: Invalid pixel values. Valid values are between 0 and max_color.'
       case ('ppm')
         if (maxval(pixels) > this%max_color .or. minval(pixels) < 0)&
         error stop 'set_pixels: Invalid pixel values. Valid values are between 0 and max_color.'
       case default
         error stop 'check_pixel_range: Invalid file format. Valid file formats are pbm, pgm, and ppm.'
      end select
   end subroutine check_pixel_range
Call graph
flip_horizontal calls check_pixel_range
flip_vertical calls check_pixel_range
greyscale calls check_pixel_range
import_pnm calls check_pixel_range
remove_channels calls check_pixel_range
set_pixel_a calls check_pixel_range
swap_channels calls check_pixel_range
demo_ppm calls flip_horizontal, flip_vertical, greyscale, import_pnm, remove_channels, swap_channels, brighten, negative, set_pnm
test10 calls import_pnm
test11 calls import_pnm
test12 calls import_pnm
test13 calls import_pnm
test14 calls import_pnm
test19 calls swap_channels, set_pnm
test20 calls remove_channels, set_pnm
test21 calls greyscale, set_pnm
test23 calls flip_horizontal, flip_vertical, set_pnm
test7 calls import_pnm
test8 calls import_pnm
test9 calls import_pnm
brighten calls set_pixels
negative calls set_pixels
set_pnm calls set_pixels
save calls set_pnm
test calls set_pnm
test1 calls set_pnm
test17 calls negative, set_pnm
test18 calls brighten, set_pnm
test2 calls set_pnm
test22 calls set_pnm
test24 calls set_pnm
test25 calls set_pnm
test3 calls set_pnm
test4 calls set_pnm
test6 calls set_pnm