cmyk_to_rgb – ForImage
cmyk_to_rgb Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
11 statements
Source File
private pure elemental subroutine cmyk_to_rgb(c, m, y, k, r, g, b)
Arguments
Type Intent Optional Attributes Name
integer(kind=ik), intent(in) :: c
integer(kind=ik), intent(in) :: m
integer(kind=ik), intent(in) :: y
integer(kind=ik), intent(in) :: k
integer(kind=ik), intent(out) :: r
integer(kind=ik), intent(out) :: g
integer(kind=ik), intent(out) :: b
Called by
Source Code
   elemental pure subroutine cmyk_to_rgb(c, m, y, k, r, g, b)
      integer(ik), intent(in)  :: c, m, y, k
      integer(ik), intent(out) :: r, g, b
      real(rk) :: cr, mg, yl
      cr = real(c, kind=rk) / 100.0_rk
      mg = real(m, kind=rk) / 100.0_rk
      yl = real(y, kind=rk) / 100.0_rk
      r = nint(255.0_rk * (1.0_rk - cr) * (1.0_rk - real(k, kind=rk) / 100.0_rk), kind=ik)
      g = nint(255.0_rk * (1.0_rk - mg) * (1.0_rk - real(k, kind=rk) / 100.0_rk), kind=ik)
      b = nint(255.0_rk * (1.0_rk - yl) * (1.0_rk - real(k, kind=rk) / 100.0_rk), kind=ik)
   end subroutine cmyk_to_rgb
Call graph
convert calls cmyk_to_rgb
initialize_colors calls convert, set
demo_color calls convert, find_nearest, print_available_colors, save_available_colors, set
example26 calls convert, set
example27 calls convert, find_nearest, set
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
set_by_name calls initialize_colors
set calls set_by_name
example29 calls print_available_colors, save_available_colors
example28 calls set