deallocate_pnm – ForImage
deallocate_pnm Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental subroutine deallocate_pnm(this)
Deallocates memory for the PNM image.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
Called by
Source Code
   elemental pure subroutine deallocate_pnm(this)
      class(format_pnm), intent(inout)    :: this
      if (allocated(this%pixels)) deallocate(this%pixels)
      if (allocated(this%comment)) deallocate(this%comment)
   end subroutine deallocate_pnm
Call graph
demo_ppm calls deallocate_pnm
test calls deallocate_pnm
test1 calls deallocate_pnm
test10 calls deallocate_pnm
test11 calls deallocate_pnm
test12 calls deallocate_pnm
test13 calls deallocate_pnm
test14 calls deallocate_pnm
test17 calls deallocate_pnm
test18 calls deallocate_pnm
test19 calls deallocate_pnm
test2 calls deallocate_pnm
test20 calls deallocate_pnm
test21 calls deallocate_pnm
test22 calls deallocate_pnm
test23 calls deallocate_pnm
test24 calls deallocate_pnm
test25 calls deallocate_pnm
test3 calls deallocate_pnm
test4 calls deallocate_pnm
test6 calls deallocate_pnm
test7 calls deallocate_pnm
test8 calls deallocate_pnm
test9 calls deallocate_pnm