decode_binary_pbm_pixels – ForImage
decode_binary_pbm_pixels Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
9 statements
Source File
private pure subroutine decode_binary_pbm_pixels(this, buffer)
Unpacks binary data from a character buffer into the image's pixel array.
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
character(len=1), intent(in) :: buffer(:)
Called by
Source Code
   pure subroutine decode_binary_pbm_pixels(this, buffer)
      class(format_pnm), intent(inout) :: this
      character(len=1), intent(in) :: buffer(:)
      integer :: row, col, nbytes
      nbytes = (this%width+7)/8
      do concurrent (row = 0:this%height-1, col = 0:this%width-1)
         this%pixels(row+1, col+1) = ibits(ichar(buffer(row*nbytes+col/8+1)), 7-mod(col, 8), 1)
      end do
   end subroutine decode_binary_pbm_pixels
Call graph
import_pnm calls decode_binary_pbm_pixels
demo_ppm calls import_pnm
test10 calls import_pnm
test11 calls import_pnm
test12 calls import_pnm
test13 calls import_pnm
test14 calls import_pnm
test7 calls import_pnm
test8 calls import_pnm
test9 calls import_pnm