export_pnm – ForImage
export_pnm Subroutine
Seyed Ali Ghasemi
58 statements
Source File
private impure subroutine export_pnm(this, file_name, encoding)
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
character(len=*), intent(in) :: file_name
character(len=*), intent(in), optional :: encoding
Calls
Called by
Source Code
   impure subroutine export_pnm(this, file_name, encoding)
      class(format_pnm), intent(inout)        :: this
      character(*),      intent(in)           :: file_name
      character(*),      intent(in), optional :: encoding
      integer                                 :: nunit, i, j
      logical                                 :: file_exists
      integer, dimension(size(this%pixels,2)) :: buffer
      integer                                 :: iostat
      if (present(encoding)) then
         call this%set_format(encoding)
         select case (this%encoding)
          case ('ascii','plain')
            select case (this%file_format)
             case ('pbm')
               this%magic_number = 'P1'
             case ('pgm')
               this%magic_number = 'P2'
             case ('ppm')
               this%magic_number = 'P3'
            end select
          case ('binary','raw')
            select case (this%file_format)
             case ('pbm')
               this%magic_number = 'P4'
             case ('pgm')
               this%magic_number = 'P5'
             case ('ppm')
               this%magic_number = 'P6'
            end select
         end select
      end if
      select case (this%magic_number)
       case ('P1', 'P2', 'P3')
         open (newunit = nunit, file = file_name//'.'//this%file_format, status='replace', iostat=iostat)
         if (iostat /= 0) error stop 'Error opening the file.'
         write(nunit,'(a)') this%magic_number
         write(nunit,'(a,a)') '# ',trim(adjustl(this%comment))
         write(nunit, '(g0,1x,g0)') this%width, this%height
         if (this%file_format /= 'pbm') write(nunit,'(g0)') this%max_color
         do i = 1, size(this%pixels,1)
            buffer = this%pixels(i,:)
            write(nunit, '(*(g0,1x))') buffer
         end do
         close(nunit)
       case ('P4', 'P5', 'P6')
         open (newunit = nunit, file = file_name//'.'//this%file_format, status='replace', iostat=iostat)
         if (iostat /= 0) error stop 'Error opening the file.'
         write(nunit,'(a)') this%magic_number
         write(nunit,'(a,a)') '# ',trim(adjustl(this%comment))
         write(nunit, '(g0,1x,g0)') this%width, this%height
         if (this%file_format /= 'pbm') write(nunit,'(g0)') this%max_color
         do i = 1, size(this%pixels,1)
            buffer = this%pixels(i,:)
            write(nunit, '(*(a))', advance='no') achar(buffer)
         end do
         close(nunit)
      end select
   end subroutine export_pnm
Call graph
export_pnm calls set_format
demo calls export_pnm
example calls export_pnm
example1 calls export_pnm
example10 calls export_pnm
example11 calls export_pnm
example12 calls export_pnm
example13 calls export_pnm
example14 calls export_pnm
example17 calls export_pnm
example18 calls export_pnm
example19 calls export_pnm
example2 calls export_pnm
example20 calls export_pnm
example21 calls export_pnm
example22 calls export_pnm
example23 calls export_pnm
example24 calls export_pnm
example25 calls export_pnm
example3 calls export_pnm
example4 calls export_pnm
example6 calls export_pnm
example7 calls export_pnm
example8 calls export_pnm
example9 calls export_pnm