find_nearest – ForImage
find_nearest Subroutine
Seyed Ali Ghasemi
24 statements
Source File
private pure elemental subroutine find_nearest(this, nearest_color)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
type(color), intent(out) :: nearest_color
Calls
Source Code
   elemental pure subroutine find_nearest(this, nearest_color)
      class(color), intent(inout) :: this
      type(color),  intent(out)   :: nearest_color
      integer(ik) :: i, closestColorIndex, ri, gi, bi
      real(rk)    :: dist, min_dist
      type(color), dimension(:), allocatable :: colors
      call initialize_colors(colors)
      min_dist = huge(min_dist)
      closestColorIndex = 0
      do concurrent (i = 1: size(colors))
         call colors(i)%get_rgb(ri, gi, bi)
         dist = sqrt(&
            (real((ri-this%r), kind=rk)/255.0_rk)**2&
            + (real((gi-this%g), kind=rk)/255.0_rk)**2&
            + (real((bi-this%b), kind=rk)/255.0_rk)**2&
            )
         if (dist < min_dist) then
            min_dist = dist
            closestColorIndex = i
         end if
      end do
      if (closestColorIndex == 0) then
         error stop 'error: no color found'
      else
         nearest_color = colors(closestColorIndex)
      end if
      call nearest_color%convert('rgb2all')
   end subroutine find_nearest
Call graph
find_nearest calls convert, get_rgb, initialize_colors
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv
initialize_colors calls convert, set
set calls set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_name, set_rgb
set_cmyk calls convert
set_decimal calls convert
set_hex calls convert
set_hsl calls convert
set_hsv calls convert
set_rgb calls convert