flip_horizontal – ForImage
flip_horizontal Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
20 statements
Source File
private pure elemental subroutine flip_horizontal(this)
Flips the image horizontally.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
Calls
Called by
Source Code
   elemental pure subroutine flip_horizontal(this)
      class(format_pnm), intent(inout) :: this
      select case (this%file_format)
       case ('pbm', 'pgm')
         this%pixels(:,:) = this%pixels(:, this%width:1:-1)
         call this%check_pixel_range(this%pixels)
       case ('ppm')
         this%pixels(:, 1:size(this%pixels, 2):3) = this%pixels(:, size(this%pixels, 2)-2:1:-3)
         this%pixels(:, 2:size(this%pixels, 2):3) = this%pixels(:, size(this%pixels, 2)-1:2:-3)
         this%pixels(:, 3:size(this%pixels, 2):3) = this%pixels(:, size(this%pixels, 2)  :3:-3)
         call this%check_pixel_range(this%pixels)
      end select
      call this%set_height(size(this%pixels,1))
      select case (this%file_format)
       case ('pbm', 'pgm')
         call this%set_width(size(this%pixels,2))
       case ('ppm')
         call this%set_width(size(this%pixels,2)/3)
      end select
   end subroutine flip_horizontal
Call graph
flip_horizontal calls check_pixel_range, set_height, set_width
demo_ppm calls flip_horizontal
test23 calls flip_horizontal