get – ForImage
get Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
15 statements
Source File
private pure elemental subroutine get(this, name, r, g, b, c, m, y, k, decimal, hex, h, s, v, hl, sl, vl, xyz_x, xyz_y, xyz_z)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
character(len=*), intent(out), optional :: name
integer(kind=ik), intent(out), optional :: r
integer(kind=ik), intent(out), optional :: g
integer(kind=ik), intent(out), optional :: b
integer(kind=ik), intent(out), optional :: c
integer(kind=ik), intent(out), optional :: m
integer(kind=ik), intent(out), optional :: y
integer(kind=ik), intent(out), optional :: k
integer(kind=ik), intent(out), optional :: decimal
character(len=7), intent(out), optional :: hex
real(kind=rk), intent(out), optional :: h
real(kind=rk), intent(out), optional :: s
real(kind=rk), intent(out), optional :: v
real(kind=rk), intent(out), optional :: hl
real(kind=rk), intent(out), optional :: sl
real(kind=rk), intent(out), optional :: vl
real(kind=rk), intent(out), optional :: xyz_x
real(kind=rk), intent(out), optional :: xyz_y
real(kind=rk), intent(out), optional :: xyz_z
Calls
Called by
Source Code
   elemental pure subroutine get(this, name, r,g,b, c,m,y,k, decimal, hex, h,s,v, hl,sl,vl, xyz_x,xyz_y,xyz_z)
      class(color), intent(inout) :: this
      character(len=*), intent(out), optional :: name
      integer(ik),  intent(out), optional :: r, g, b, c, m, y, k, decimal
      character(len=7), intent(out), optional :: hex
      real(rk),     intent(out), optional :: h, s, v, hl, sl, vl, xyz_x, xyz_y, xyz_z
      if (present(name))                                                 call this%get_name(name)
      if (present(r) .and. present(g) .and. present(b))                  call this%get_rgb(r, g, b)
      if (present(c) .and. present(m) .and. present(y) .and. present(k)) call this%get_cmyk(c, m, y, k)
      if (present(decimal))                                              call this%get_decimal(decimal)
      if (present(hex))                                                  call this%get_hex(hex)
      if (present(h) .and. present(s) .and. present(v))                  call this%get_hsv(h, s, v)
      if (present(hl) .and. present(sl) .and. present(vl))               call this%get_hsl(hl, sl, vl)
      if (present(xyz_x) .and. present(xyz_y) .and. present(xyz_z))      call this%get_xyz(xyz_x, xyz_y, xyz_z)
   end subroutine get
Call graph
get calls get_cmyk, get_decimal, get_hex, get_hsl, get_hsv, get_name, get_rgb, get_xyz
demo_color calls get
example26 calls get