get_rgb – ForImage
get_rgb Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
7 statements
Source File
private pure elemental subroutine get_rgb(this, r, g, b)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(in) :: this
integer(kind=ik), intent(out) :: r
integer(kind=ik), intent(out) :: g
integer(kind=ik), intent(out) :: b
Called by
Source Code
   elemental pure subroutine get_rgb(this, r, g, b)
      class(color), intent(in)  :: this
      integer(ik),  intent(out) :: r, g, b
      r = this%r
      g = this%g
      b = this%b
   end subroutine get_rgb
Call graph
find_nearest calls get_rgb
get calls get_rgb
demo_color calls find_nearest, get
example26 calls get
example27 calls find_nearest