get_hsl – ForImage
get_hsl Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
7 statements
Source File
private pure elemental subroutine get_hsl(this, h, s, l)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(in) :: this
real(kind=rk), intent(out) :: h
real(kind=rk), intent(out) :: s
real(kind=rk), intent(out) :: l
Called by
Source Code
   elemental pure subroutine get_hsl(this, h, s, l)
      class(color), intent(in)  :: this
      real(rk),    intent(out) :: h, s, l
      h = this%hl
      s = this%sl
      l = this%vl
   end subroutine get_hsl
Call graph
get calls get_hsl
demo_color calls get
example26 calls get