hex_to_rgb – ForImage
hex_to_rgb Subroutine
Seyed Ali Ghasemi
7 statements
Source File
private pure elemental subroutine hex_to_rgb(hex, r, g, b)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: hex
integer(kind=ik), intent(out) :: r
integer(kind=ik), intent(out) :: g
integer(kind=ik), intent(out) :: b
Called by
Source Code
   elemental pure subroutine hex_to_rgb(hex, r, g, b)
      character(len=*), intent(in)  :: hex
      integer(ik),      intent(out) :: r, g, b
      read(hex(2:3), '(z2)') r
      read(hex(4:5), '(z2)') g
      read(hex(6:7), '(z2)') b
   end subroutine hex_to_rgb
Call graph
convert calls hex_to_rgb
find_nearest calls convert, initialize_colors
initialize_colors calls convert, set
set_cmyk calls convert
set_decimal calls convert
set_hex calls convert
set_hsl calls convert
set_hsv calls convert
set_rgb calls convert
pick calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
set calls set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_rgb