initialize_colors – ForImage
initialize_colors Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
61 statements
Source File
private pure subroutine initialize_colors(colors)
Arguments
Type Intent Optional Attributes Name
type(color), intent(out), dimension(:), allocatable :: colors
Calls
Called by
Source Code
   pure subroutine initialize_colors(colors)
      type(color), intent(out), dimension(:), allocatable :: colors
      allocate(colors(14))
      colors(1)%color_name  = 'red'    ; colors(1)%r  = 255_ik ; colors(1)%g  =   0_ik ; colors(1)%b  =   0_ik
      colors(2)%color_name  = 'green'  ; colors(2)%r  =   0_ik ; colors(2)%g  = 128_ik ; colors(2)%b  =   0_ik
      colors(3)%color_name  = 'blue'   ; colors(3)%r  =   0_ik ; colors(3)%g  =   0_ik ; colors(3)%b  = 255_ik
      colors(4)%color_name  = 'yellow' ; colors(4)%r  = 255_ik ; colors(4)%g  = 255_ik ; colors(4)%b  =   0_ik
      colors(5)%color_name  = 'cyan'   ; colors(5)%r  =   0_ik ; colors(5)%g  = 255_ik ; colors(5)%b  = 255_ik
      colors(6)%color_name  = 'magenta'; colors(6)%r  = 255_ik ; colors(6)%g  =   0_ik ; colors(6)%b  = 255_ik
      colors(7)%color_name  = 'black'  ; colors(7)%r  =   0_ik ; colors(7)%g  =   0_ik ; colors(7)%b  =   0_ik
      colors(8)%color_name  = 'white'  ; colors(8)%r  = 255_ik ; colors(8)%g  = 255_ik ; colors(8)%b  = 255_ik
      colors(9)%color_name  = 'gray'   ; colors(9)%r  = 128_ik ; colors(9)%g  = 128_ik ; colors(9)%b  = 128_ik
      colors(10)%color_name = 'brown'  ; colors(10)%r = 165_ik ; colors(10)%g =  42_ik ; colors(10)%b =  42_ik
      colors(11)%color_name = 'orange' ; colors(11)%r = 255_ik ; colors(11)%g = 165_ik ; colors(11)%b =   0_ik
      colors(12)%color_name = 'gold'   ; colors(12)%r = 255_ik ; colors(12)%g = 215_ik ; colors(12)%b =   0_ik
      colors(13)%color_name = 'pink'   ; colors(13)%r = 255_ik ; colors(13)%g = 192_ik ; colors(13)%b = 203_ik
      colors(14)%color_name = 'violet' ; colors(14)%r = 138_ik ; colors(14)%g =  43_ik ; colors(14)%b = 226_ik
      call colors(:)%convert('rgb2all')
   end subroutine initialize_colors
Call graph
initialize_colors calls convert
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv, rgb_to_xyz, xyz_to_rgb
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
set_by_name calls initialize_colors
set calls set_by_name
demo_color calls find_nearest, print_available_colors, save_available_colors, set
example27 calls find_nearest, set
example29 calls print_available_colors, save_available_colors
example26 calls set
example28 calls set