negative – ForImage
negative Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
4 statements
Source File
private pure elemental subroutine negative(this)
Inverts the colors of the image.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
Calls
Called by
Source Code
   elemental pure subroutine negative(this)
      class(format_pnm), intent(inout) :: this
      call this%set_pixels(this%max_color - this%pixels)
   end subroutine negative
Call graph
negative calls set_pixels
set_pixels calls check_pixel_range
demo_ppm calls negative
test17 calls negative