pick – ForImage
pick Subroutine
Seyed Ali Ghasemi
12 statements
Source File
private pure elemental subroutine pick(this, name)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
character(len=*), intent(in) :: name
Calls
Source Code
   elemental pure subroutine pick(this, name)
      class(color),     intent(inout) :: this
      character(len=*), intent(in)    :: name
      type(color), dimension(:), allocatable       :: colors
      integer                         :: i
      call initialize_colors(colors)
      do concurrent (i = 1: size(colors))
         if (trim(colors(i)%color_name) == trim(name)) then
            this = colors(i)
         end if
      end do
   end subroutine pick
Call graph
pick calls initialize_colors
initialize_colors calls convert, set
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv
set calls set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_name, set_rgb
set_cmyk calls convert
set_decimal calls convert
set_hex calls convert
set_hsl calls convert
set_hsv calls convert
set_rgb calls convert