print – ForImage
print Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
44 statements
Source File
private impure elemental subroutine print(this, option)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
character(len=*), intent(in), optional :: option
Calls
Source Code
   elemental impure subroutine print(this, option)
      class(color), intent(inout) :: this
      character(len=*), intent(in), optional :: option
      if (present(option)) then
         select case (trim(option))
          case ('rgb')
            call this%print_rgb()
            print*,''
          case ('hex')
            call this%print_hex()
            print*,''
          case ('decimal')
            call this%print_decimal()
            print*,''
          case ('cmyk')
            call this%print_cmyk()
            print*,''
          case ('hsv')
            call this%print_hsv()
            print*,''
          case ('hsl')
            call this%print_hsl()
            print*,''
          case ('name')
            call this%print_name()
            print*,''
          case ('xyz')
            call this%print_xyz()
            print*,''
          case default
            error stop 'error: unknown option'
         end select
      else
         call this%print_name()
         call this%print_rgb()
         call this%print_hex()
         call this%print_decimal()
         call this%print_cmyk()
         call this%print_hsv()
         call this%print_hsl()
         call this%print_xyz()
         print*,''
      end if
   end subroutine print
Call graph
print calls print_cmyk, print_decimal, print_hex, print_hsl, print_hsv, print_name, print_rgb, print_xyz