rgb_to_cmyk – ForImage
rgb_to_cmyk Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
23 statements
Source File
private pure elemental subroutine rgb_to_cmyk(r, g, b, c, m, y, k)
Arguments
Type Intent Optional Attributes Name
integer(kind=ik), intent(in) :: r
integer(kind=ik), intent(in) :: g
integer(kind=ik), intent(in) :: b
integer(kind=ik), intent(out) :: c
integer(kind=ik), intent(out) :: m
integer(kind=ik), intent(out) :: y
integer(kind=ik), intent(out) :: k
Called by
Source Code
   elemental pure subroutine rgb_to_cmyk(r, g, b, c, m, y, k)
      integer(ik), intent(in)  :: r, g, b
      integer(ik), intent(out) :: c, m, y, k
      real(rk)                 :: rn, gn, bn
      real(rk)                 :: cr, mr, yr, kr
      rn = r/255.0_rk
      gn = g/255.0_rk
      bn = b/255.0_rk
      kr = 1.0_rk - max(rn, gn, bn)
      if (abs(kr - 1.0_rk) < 1.0e-6_rk) then
         cr = 0.0_rk
         mr = 0.0_rk
         yr = 0.0_rk
      else
         cr = (1.0_rk-rn-kr)/(1.0_rk-kr)
         mr = (1.0_rk-gn-kr)/(1.0_rk-kr)
         yr = (1.0_rk-bn-kr)/(1.0_rk-kr)
      end if
      c = nint(cr*100.0_rk, kind=ik)
      m = nint(mr*100.0_rk, kind=ik)
      y = nint(yr*100.0_rk, kind=ik)
      k = nint(kr*100.0_rk, kind=ik)
   end subroutine rgb_to_cmyk
Call graph
convert calls rgb_to_cmyk
initialize_colors calls convert, set
demo_color calls convert, find_nearest, print_available_colors, save_available_colors, set
example26 calls convert, set
example27 calls convert, find_nearest, set
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
set_by_name calls initialize_colors
set calls set_by_name
example29 calls print_available_colors, save_available_colors
example28 calls set