rgb_to_decimal – ForImage
rgb_to_decimal Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
6 statements
Source File
private pure elemental subroutine rgb_to_decimal(r, g, b, decimal)
Arguments
Type Intent Optional Attributes Name
integer(kind=ik), intent(in) :: r
integer(kind=ik), intent(in) :: g
integer(kind=ik), intent(in) :: b
integer(kind=ik), intent(out) :: decimal
Called by
Source Code
   elemental pure subroutine rgb_to_decimal(r, g, b, decimal)
      implicit none
      integer(ik), intent(in)  :: r, g, b
      integer(ik), intent(out) :: decimal
      decimal = r*65536_ik + g*256_ik + b
   end subroutine rgb_to_decimal
Call graph
convert calls rgb_to_decimal
initialize_colors calls convert
demo_color calls convert, find_nearest, print_available_colors, save_available_colors, set
example26 calls convert, set
example27 calls convert, find_nearest, set
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
set_by_name calls initialize_colors
set calls set_by_name
example29 calls print_available_colors, save_available_colors
example28 calls set