save – ForImage
save Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
28 statements
Source File
private impure elemental subroutine save(this, file_name, height, width)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
integer, intent(in), optional :: height
integer, intent(in), optional :: width
Calls
Source Code
   elemental impure subroutine save(this, file_name, height, width)
      class(color), intent(inout) :: this
      character(len=*), intent(in), optional :: file_name
      integer, intent(in), optional :: height, width
      type(format_pnm) :: image
      integer :: height_, width_
      integer(ik), dimension(:,:), allocatable :: px
      if (present(height)) then
         height_ = height
      else
         height_ = 50
      end if
      if (present(width)) then
         width_ = width
      else
         width_ = 50
      end if
      allocate(px(height_, 3*width_))
      px(:,1:3*width_-2:3) = this%r
      px(:,2:3*width_-1:3) = this%g
      px(:,3:3*width_-0:3) = this%b
      call image%set_pnm(&
         encoding    = 'binary', &
         file_format = 'ppm', &
         width       = width_, &
         height      = height_, &
         max_color   = 255, &
         comment     = trim(this%color_name), &
         pixels      = px &
         )
      if (present(file_name)) then
         call image%export_pnm(trim(file_name))
      else
         call image%export_pnm('pnm_files/colors/'//trim(this%color_name))
      end if
   end subroutine save
Call graph
save calls export_pnm, set_pnm
export_pnm calls encode_binary_pbm_pixels, set_format, write_header
set_pnm calls set_pixels, allocate_pixels, set_file_format, set_format, set_header
set_header calls set_comment, set_height, set_magicnumber, set_max_color, set_width
set_pixel_a calls check_pixel_range