save_available_colors – ForImage
save_available_colors Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
8 statements
Source File
private impure elemental subroutine save_available_colors(this, file_name, height, width)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
character(len=*), intent(in), optional :: file_name
integer, intent(in), optional :: height
integer, intent(in), optional :: width
Calls
Called by
Source Code
   elemental impure subroutine save_available_colors(this, file_name, height, width)
      class(color), intent(inout) :: this
      character(len=*), intent(in), optional :: file_name
      integer, intent(in), optional  :: height, width
      type(color), dimension(:), allocatable :: colors
      call initialize_colors(colors)
      call colors(:)%save(file_name, height, width)
   end subroutine save_available_colors
Call graph
save_available_colors calls initialize_colors
initialize_colors calls convert, set
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv, rgb_to_xyz, xyz_to_rgb
set calls set_by_name, set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_name, set_rgb, set_xyz
set_by_name calls initialize_colors
demo_color calls save_available_colors
example29 calls save_available_colors