set_file_format – ForImage
set_file_format Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental subroutine set_file_format(this, file_format)
Sets the file format of the PNM image. Supported values are pbm, pgm, and ppm.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
character(len=3), intent(in) :: file_format
Called by
Source Code
   elemental pure subroutine set_file_format(this, file_format)
      class(format_pnm), intent(inout) :: this
      character(3), intent(in)         :: file_format
      this%file_format = file_format
   end subroutine set_file_format
Call graph
import_pnm calls set_file_format
set_pnm calls set_file_format
save calls set_pnm
demo_ppm calls import_pnm, set_pnm
test calls set_pnm
test1 calls set_pnm
test10 calls import_pnm
test11 calls import_pnm
test12 calls import_pnm
test13 calls import_pnm
test14 calls import_pnm
test17 calls set_pnm
test18 calls set_pnm
test19 calls set_pnm
test2 calls set_pnm
test20 calls set_pnm
test21 calls set_pnm
test22 calls set_pnm
test23 calls set_pnm
test24 calls set_pnm
test25 calls set_pnm
test3 calls set_pnm
test4 calls set_pnm
test6 calls set_pnm
test7 calls import_pnm
test8 calls import_pnm
test9 calls import_pnm