set_comment – ForImage
set_comment Subroutine
Seyed Ali Ghasemi
5 statements
Source File
private pure elemental subroutine set_comment(this, comment)
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
character(len=*), intent(in) :: comment
Called by
Source Code
   elemental pure subroutine set_comment(this, comment)
      class(format_pnm), intent(inout) :: this
      character(*), intent(in)         :: comment
      this%comment = comment
   end subroutine set_comment
Call graph
set_header calls set_comment
set_pnm calls set_header
example calls set_pnm
example1 calls set_pnm
example17 calls set_pnm
example18 calls set_pnm
example2 calls set_pnm
example3 calls set_pnm
example4 calls set_pnm
example6 calls set_pnm