set_height – ForImage
set_height Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental subroutine set_height(this, height)
Sets the height of the PNM image.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
integer, intent(in) :: height
Called by
Source Code
   elemental pure subroutine set_height(this, height)
      class(format_pnm), intent(inout) :: this
      integer, intent(in)              :: height
      this%height = height
   end subroutine set_height
Call graph
crop calls set_height
flip_horizontal calls set_height
flip_vertical calls set_height
resize calls set_height
rotate calls set_height
set_header calls set_height
set_pnm calls set_header
demo_ppm calls crop, flip_horizontal, flip_vertical, resize, rotate, set_pnm
test22 calls rotate, set_pnm
test23 calls flip_horizontal, flip_vertical, set_pnm
test24 calls crop, set_pnm
test25 calls resize, set_pnm
save calls set_pnm
test calls set_pnm
test1 calls set_pnm
test17 calls set_pnm
test18 calls set_pnm
test19 calls set_pnm
test2 calls set_pnm
test20 calls set_pnm
test21 calls set_pnm
test3 calls set_pnm
test4 calls set_pnm
test6 calls set_pnm