set_name – ForImage
set_name Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental subroutine set_name(this, name)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
character(len=*), intent(in) :: name
Called by
Source Code
   elemental pure subroutine set_name(this, name)
      class(color), intent(inout) :: this
      character(len=*), intent(in) :: name
      this%color_name = trim(name)
   end subroutine set_name
Call graph
set calls set_name, set_by_name
initialize_colors calls set
demo_color calls set, find_nearest, print_available_colors, save_available_colors
example26 calls set
example27 calls set, find_nearest
example28 calls set
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
set_by_name calls initialize_colors
example29 calls print_available_colors, save_available_colors