set_pnm – ForImage
set_pnm Subroutine
Seyed Ali Ghasemi
36 statements
Source File
private pure subroutine set_pnm(this, encoding, file_format, width, height, max_color, comment, pixels)
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
character(len=*), intent(in) :: encoding
character(len=3), intent(in) :: file_format
integer, intent(in) :: width
integer, intent(in) :: height
integer, intent(in), optional :: max_color
character(len=*), intent(in) :: comment
integer, intent(in), dimension(:,:) :: pixels
Calls
Called by
Source Code
   pure subroutine set_pnm(this, encoding, file_format,width,height,max_color,comment,pixels)
      class(format_pnm), intent(inout)    :: this
      integer, intent(in)                 :: width
      integer, intent(in)                 :: height
      character(*), intent(in)            :: comment
      integer, optional, intent(in)       :: max_color
      integer, dimension(:,:), intent(in) :: pixels
      character(*), intent(in)            :: encoding
      character(3), intent(in)            :: file_format
      character(2)                        :: magic_number
      call this%set_format(encoding)
      call this%set_file_format(file_format)
      select case (this%encoding)
       case ('ascii','plain')
         select case (this%file_format)
          case ('pbm')
            magic_number = 'P1'
          case ('pgm')
            magic_number = 'P2'
          case ('ppm')
            magic_number = 'P3'
         end select
       case ('binary','raw')
         select case (this%file_format)
          case ('pbm')
            magic_number = 'P4'
          case ('pgm')
            magic_number = 'P5'
          case ('ppm')
            magic_number = 'P6'
         end select
      end select
      call this%set_header(magic_number,width,height,comment,max_color)
      call this%allocate_pixels()
      call this%set_pixels(pixels)
   end subroutine set_pnm
Call graph
set_pnm calls allocate_pixels, set_file_format, set_format, set_header, set_pixels
set_header calls set_comment, set_height, set_magicnumber, set_max_color, set_width
set_pixels calls check_pixel_range
demo calls set_pnm
example calls set_pnm
example1 calls set_pnm
example17 calls set_pnm
example18 calls set_pnm
example19 calls set_pnm
example2 calls set_pnm
example20 calls set_pnm
example21 calls set_pnm
example22 calls set_pnm
example23 calls set_pnm
example24 calls set_pnm
example3 calls set_pnm
example4 calls set_pnm
example6 calls set_pnm