set_pixels – ForImage
set_pixels Subroutine
Seyed Ali Ghasemi
6 statements
Source File
private pure subroutine set_pixels(this, pixels)
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
integer, intent(in), dimension(:,:) :: pixels
Calls
Called by
Source Code
   pure subroutine set_pixels(this, pixels)
      class(format_pnm), intent(inout) :: this
      integer, dimension(:,:), intent(in) :: pixels
      call this%check_pixel_range(pixels)
      this%pixels = pixels
   end subroutine set_pixels
Call graph
set_pixels calls check_pixel_range
brighten calls set_pixels
crop calls set_pixels
import_pnm calls set_pixels
negative calls set_pixels
resize calls set_pixels
rotate calls set_pixels
set_pnm calls set_pixels
demo calls brighten, crop, import_pnm, negative, resize, rotate, set_pnm
example calls set_pnm
example1 calls set_pnm
example10 calls import_pnm
example11 calls import_pnm
example12 calls import_pnm
example13 calls import_pnm
example14 calls import_pnm
example17 calls negative, set_pnm
example18 calls brighten, set_pnm
example19 calls set_pnm
example2 calls set_pnm
example20 calls set_pnm
example21 calls set_pnm
example22 calls rotate, set_pnm
example23 calls set_pnm
example24 calls crop, set_pnm
example25 calls resize, set_pnm
example3 calls set_pnm
example4 calls set_pnm
example6 calls set_pnm
example7 calls import_pnm
example8 calls import_pnm
example9 calls import_pnm