set_cmyk – ForImage
set_cmyk Subroutine
Seyed Ali Ghasemi
8 statements
Source File
private pure elemental subroutine set_cmyk(this, c, m, y, k)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
integer(kind=ik), intent(in) :: c
integer(kind=ik), intent(in) :: m
integer(kind=ik), intent(in) :: y
integer(kind=ik), intent(in) :: k
Called by
Source Code
   elemental pure subroutine set_cmyk(this, c, m, y, k)
      class(color), intent(inout) :: this
      integer(ik),  intent(in)    :: c, m, y, k
      this%c = c
      this%m = m
      this%y = y
      this%k = k
   end subroutine set_cmyk
Call graph
set calls set_cmyk, set_by_name
initialize_colors calls set
demo_color calls set, find_nearest, print_available_colors, save_available_colors
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
set_by_name calls initialize_colors