set_width – ForImage
set_width Subroutine
Seyed Ali Ghasemi
5 statements
Source File
private pure elemental subroutine set_width(this, width)
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
integer, intent(in) :: width
Called by
Source Code
   elemental pure subroutine set_width(this, width)
      class(format_pnm), intent(inout) :: this
      integer, intent(in)              :: width
      this%width = width
   end subroutine set_width
Call graph
set_header calls set_width
set_pnm calls set_header
demo calls set_pnm
example calls set_pnm
example1 calls set_pnm
example17 calls set_pnm
example18 calls set_pnm
example19 calls set_pnm
example2 calls set_pnm
example20 calls set_pnm
example21 calls set_pnm
example22 calls set_pnm
example23 calls set_pnm
example24 calls set_pnm
example25 calls set_pnm
example3 calls set_pnm
example4 calls set_pnm
example6 calls set_pnm