set_by_name – ForImage
set_by_name Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
30 statements
Source File
private pure elemental subroutine set_by_name(this, name)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
character(len=*), intent(in) :: name
Calls
Called by
Source Code
   elemental pure subroutine set_by_name(this, name)
      class(color),     intent(inout)        :: this
      character(len=*), intent(in)           :: name
      type(color), dimension(:), allocatable :: colors
      integer                                :: i
      call initialize_colors(colors)
#if defined(__NVCOMPILER)
      do i = 1, size(colors)
#else
      do concurrent (i = 1: size(colors))
#endif
         if (trim(colors(i)%color_name) == trim(name)) then
            ! this = colors(i)
            ! this = colors(i) relplaced by the following lines to avoid flang compiler issue
            this%r = colors(i)%r
            this%g = colors(i)%g
            this%b = colors(i)%b
            this%c = colors(i)%c
            this%m = colors(i)%m
            this%y = colors(i)%y
            this%k = colors(i)%k
            this%decimal = colors(i)%decimal
            this%hex = colors(i)%hex
            this%h = colors(i)%h
            this%s = colors(i)%s
            this%v = colors(i)%v
            this%hl = colors(i)%hl
            this%sl = colors(i)%sl
            this%vl = colors(i)%vl
            this%xyz_x = colors(i)%xyz_x
            this%xyz_y = colors(i)%xyz_y
            this%xyz_z = colors(i)%xyz_z
            this%color_name = colors(i)%color_name
         end if
      end do
   end subroutine set_by_name
Call graph
set_by_name calls initialize_colors
initialize_colors calls convert, set
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv, rgb_to_xyz, xyz_to_rgb
set calls set_by_name, set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_name, set_rgb, set_xyz
demo_color calls set, find_nearest, print_available_colors, save_available_colors
example26 calls set
example27 calls set, find_nearest
example28 calls set
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
example29 calls print_available_colors, save_available_colors