set_max_color – ForImage
set_max_color Subroutine
Seyed Ali Ghasemi
5 statements
Source File
private pure elemental subroutine set_max_color(this, max_color)
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
integer, intent(in) :: max_color
Called by
Source Code
   elemental pure subroutine set_max_color(this, max_color)
      class(format_pnm), intent(inout) :: this
      integer, intent(in)              :: max_color
      this%max_color = max_color
   end subroutine set_max_color
Call graph
set_header calls set_max_color
set_pnm calls set_header
example calls set_pnm
example1 calls set_pnm
example17 calls set_pnm
example2 calls set_pnm
example3 calls set_pnm
example4 calls set_pnm
example6 calls set_pnm