set_xyz – ForImage
set_xyz Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
7 statements
Source File
private pure elemental subroutine set_xyz(this, x, y, z)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
real(kind=rk), intent(in) :: x
real(kind=rk), intent(in) :: y
real(kind=rk), intent(in) :: z
Called by
Source Code
   elemental pure subroutine set_xyz(this, x, y, z)
      class(color), intent(inout) :: this
      real(rk),    intent(in)    :: x, y, z
      this%xyz_x = x
      this%xyz_y = y
      this%xyz_z = z
   end subroutine set_xyz
Call graph
set calls set_xyz, set_by_name
initialize_colors calls set
demo_color calls set, find_nearest, print_available_colors, save_available_colors
example26 calls set
example27 calls set, find_nearest
example28 calls set
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
set_by_name calls initialize_colors
example29 calls print_available_colors, save_available_colors