set_header – ForImage
set_header Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
13 statements
Source File
private pure elemental subroutine set_header(this, magic_number, width, height, comment, max_color)
Sets the header of the PNM image. The header includes the magic number, width, height, comment, and max_color.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
character(len=*), intent(in) :: magic_number
integer, intent(in) :: width
integer, intent(in) :: height
character(len=*), intent(in) :: comment
integer, intent(in), optional :: max_color
Calls
Called by
Source Code
   elemental pure subroutine set_header(this, magic_number, width, height, comment, max_color)
      class(format_pnm), intent(inout) :: this
      character(*), intent(in)         :: magic_number
      integer, intent(in)              :: width
      integer, intent(in)              :: height
      character(*), intent(in)         :: comment
      integer, optional, intent(in)    :: max_color
      call this%set_magicnumber(magic_number)
      call this%set_width(width)
      call this%set_height(height)
      call this%set_comment(comment)
      if (this%file_format /= 'pbm') call this%set_max_color(max_color)
   end subroutine set_header
Call graph
set_header calls set_comment, set_height, set_magicnumber, set_max_color, set_width
set_pnm calls set_header
save calls set_pnm
demo_ppm calls set_pnm
test calls set_pnm
test1 calls set_pnm
test17 calls set_pnm
test18 calls set_pnm
test19 calls set_pnm
test2 calls set_pnm
test20 calls set_pnm
test21 calls set_pnm
test22 calls set_pnm
test23 calls set_pnm
test24 calls set_pnm
test25 calls set_pnm
test3 calls set_pnm
test4 calls set_pnm
test6 calls set_pnm