set_hsl – ForImage
set_hsl Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
7 statements
Source File
private pure elemental subroutine set_hsl(this, h, s, l)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
real(kind=rk), intent(in) :: h
real(kind=rk), intent(in) :: s
real(kind=rk), intent(in) :: l
Called by
Source Code
   elemental pure subroutine set_hsl(this, h, s, l)
      class(color), intent(inout) :: this
      real(rk),    intent(in)    :: h, s, l
      this%hl = h
      this%sl = s
      this%vl = l
   end subroutine set_hsl
Call graph
set calls set_hsl
demo_color calls set
example26 calls set
example27 calls set
example28 calls set