set_magicnumber – ForImage
set_magicnumber Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental subroutine set_magicnumber(this, magic_number)
Sets the magic number of the PNM image. Supported values are P1, P2, P3, P4, P5, and P6.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
character(len=*), intent(in) :: magic_number
Called by
Source Code
   elemental pure subroutine set_magicnumber(this, magic_number)
      class(format_pnm), intent(inout) :: this
      character(*), intent(in)         :: magic_number
      this%magic_number = magic_number
   end subroutine set_magicnumber
Call graph
set_header calls set_magicnumber
set_pnm calls set_header
save calls set_pnm
demo_ppm calls set_pnm
test calls set_pnm
test1 calls set_pnm
test17 calls set_pnm
test18 calls set_pnm
test19 calls set_pnm
test2 calls set_pnm
test20 calls set_pnm
test21 calls set_pnm
test22 calls set_pnm
test23 calls set_pnm
test24 calls set_pnm
test25 calls set_pnm
test3 calls set_pnm
test4 calls set_pnm
test6 calls set_pnm