set_format – ForImage
set_format Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
5 statements
Source File
private pure elemental subroutine set_format(this, encoding)
Sets the encoding of the PNM image. Supported values are ascii or plain and binary or raw.
Type Bound
format_pnm
Arguments
Type Intent Optional Attributes Name
class(format_pnm), intent(inout) :: this
character(len=*), intent(in) :: encoding
Called by
Source Code
   elemental pure subroutine set_format(this, encoding)
      class(format_pnm), intent(inout) :: this
      character(*), intent(in)         :: encoding
      this%encoding = trim(encoding)
   end subroutine set_format
Call graph
export_pnm calls set_format
import_pnm calls set_format
set_pnm calls set_format
save calls export_pnm, set_pnm
demo_ppm calls export_pnm, import_pnm, set_pnm
test calls export_pnm, set_pnm
test1 calls export_pnm, set_pnm
test10 calls export_pnm, import_pnm
test11 calls export_pnm, import_pnm
test12 calls export_pnm, import_pnm
test13 calls export_pnm, import_pnm
test14 calls export_pnm, import_pnm
test17 calls export_pnm, set_pnm
test18 calls export_pnm, set_pnm
test19 calls export_pnm, set_pnm
test2 calls export_pnm, set_pnm
test20 calls export_pnm, set_pnm
test21 calls export_pnm, set_pnm
test22 calls export_pnm, set_pnm
test23 calls export_pnm, set_pnm
test24 calls export_pnm, set_pnm
test25 calls export_pnm, set_pnm
test3 calls export_pnm, set_pnm
test4 calls export_pnm, set_pnm
test6 calls export_pnm, set_pnm
test7 calls export_pnm, import_pnm
test8 calls export_pnm, import_pnm
test9 calls export_pnm, import_pnm