set_decimal – ForImage
set_decimal Subroutine
Seyed Ali Ghasemi
6 statements
Source File
private pure elemental subroutine set_decimal(this, decimal)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
integer(kind=ik), intent(in) :: decimal
Calls
Called by
Source Code
   elemental pure subroutine set_decimal(this, decimal)
      class(color), intent(inout) :: this
      integer(ik),  intent(in)    :: decimal
      this%decimal = decimal
      call this%convert('decimal2all')
   end subroutine set_decimal
Call graph
set_decimal calls convert
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv
set calls set_decimal
initialize_colors calls set
find_nearest calls initialize_colors
pick calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors