set – ForImage
set Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
26 statements
Source File
private pure elemental subroutine set(this, name, r, g, b, c, m, y, k, decimal, hex, h, s, v, hl, sl, vl, xyz_x, xyz_y, xyz_z, use_library)
Type Bound
color
Arguments
Type Intent Optional Attributes Name
class(color), intent(inout) :: this
character(len=*), intent(in) :: name
integer(kind=ik), intent(in), optional :: r
integer(kind=ik), intent(in), optional :: g
integer(kind=ik), intent(in), optional :: b
integer(kind=ik), intent(in), optional :: c
integer(kind=ik), intent(in), optional :: m
integer(kind=ik), intent(in), optional :: y
integer(kind=ik), intent(in), optional :: k
integer(kind=ik), intent(in), optional :: decimal
character(len=*), intent(in), optional :: hex
real(kind=rk), intent(in), optional :: h
real(kind=rk), intent(in), optional :: s
real(kind=rk), intent(in), optional :: v
real(kind=rk), intent(in), optional :: hl
real(kind=rk), intent(in), optional :: sl
real(kind=rk), intent(in), optional :: vl
real(kind=rk), intent(in), optional :: xyz_x
real(kind=rk), intent(in), optional :: xyz_y
real(kind=rk), intent(in), optional :: xyz_z
logical, intent(in), optional :: use_library
Calls
Called by
Source Code
   elemental pure subroutine set(this, name, r,g,b, c,m,y,k, decimal, hex, h,s,v, hl,sl,vl, xyz_x,xyz_y,xyz_z, use_library)
      class(color), intent(inout) :: this
      character(len=*), intent(in) :: name
      integer(ik),  intent(in), optional :: r, g, b, c, m, y, k, decimal
      character(len=*), intent(in), optional :: hex
      real(rk),     intent(in), optional :: h, s, v, hl, sl, vl, xyz_x, xyz_y, xyz_z
      logical,      intent(in), optional :: use_library
      logical :: use_library_
      if (present(use_library)) then
         use_library_ = use_library
      else
         use_library_ = .false.
      end if
      if (use_library_) then
         call this%set_by_name(name)
      else
         call this%set_name(name)
         if (present(r) .and. present(g) .and. present(b))                  call this%set_rgb(r, g, b)
         if (present(c) .and. present(m) .and. present(y) .and. present(k)) call this%set_cmyk(c, m, y, k)
         if (present(decimal))                                              call this%set_decimal(decimal)
         if (present(hex))                                                  call this%set_hex(hex)
         if (present(h) .and. present(s) .and. present(v))                  call this%set_hsv(h, s, v)
         if (present(hl) .and. present(sl) .and. present(vl))               call this%set_hsl(hl, sl, vl)
         if (present(xyz_x) .and. present(xyz_y) .and. present(xyz_z))      call this%set_xyz(xyz_x, xyz_y, xyz_z)
      end if
   end subroutine set
Call graph
set calls set_by_name, set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_name, set_rgb, set_xyz
set_by_name calls initialize_colors
initialize_colors calls set, convert
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv, rgb_to_xyz, xyz_to_rgb
demo_color calls set, find_nearest, print_available_colors, save_available_colors
example26 calls set
example27 calls set, find_nearest
example28 calls set
find_nearest calls initialize_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
example29 calls print_available_colors, save_available_colors