write_header – ForImage
write_header Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private subroutine write_header(this, nunit)
Writes the header of the PNM image to a file. Required before writing the pixels to the file.
Arguments
Type Intent Optional Attributes Name
type(format_pnm), intent(in) :: this
integer, intent(in) :: nunit
Called by
Source Code
   subroutine write_header(this, nunit)
      type(format_pnm), intent(in) :: this
      integer, intent(in)           :: nunit
      integer :: i, k
      ! Write magic number
      write(nunit,'(a)') this%magic_number
      ! Write comments
      k = ceiling(real(len(adjustl(this%comment)))/70.0)
      if (len(adjustl(this%comment)) /=0 .and. len(adjustl(this%comment)) <= 70) then
         write(nunit,'(a,a)') '# ',trim(adjustl(this%comment))
      else if (len(adjustl(this%comment)) /=0 .and. len(adjustl(this%comment)) > 70 ) then
         do i = 1, k-1
            write(nunit,'(a,a)') '# ',adjustl(this%comment(70*(i-1)+1:70*(i-1)+70))
         end do
         write(nunit,'(a,a)') '# ',trim(adjustl(this%comment(70*(k-1)+1:)))
      end if
      ! Write width, height and max_color
      write(nunit, '(g0,1x,g0)') this%width, this%height
      if (this%file_format /= 'pbm') write(nunit,'(g0)') this%max_color
   end subroutine write_header
Call graph
export_pnm calls write_header
save calls export_pnm
demo_ppm calls export_pnm
test calls export_pnm
test1 calls export_pnm
test10 calls export_pnm
test11 calls export_pnm
test12 calls export_pnm
test13 calls export_pnm
test14 calls export_pnm
test17 calls export_pnm
test18 calls export_pnm
test19 calls export_pnm
test2 calls export_pnm
test20 calls export_pnm
test21 calls export_pnm
test22 calls export_pnm
test23 calls export_pnm
test24 calls export_pnm
test25 calls export_pnm
test3 calls export_pnm
test4 calls export_pnm
test6 calls export_pnm
test7 calls export_pnm
test8 calls export_pnm
test9 calls export_pnm