example11 – ForImage
example11 Program
8 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: ex11
Source Code
program example11
    use forimage, only: format_pnm
    implicit none
    type(format_pnm) :: ex11
    call ex11%import_pnm('pnm_files/example5_binary','pgm','binary')
    call ex11%export_pnm('pnm_files/example5_binary_ex')
    call ex11%finalize()
end program example11
Call graph
example11 calls deallocate_pnm, export_pnm, import_pnm
export_pnm calls set_format
import_pnm calls allocate_pixels, set_file_format, set_format