example28 – ForImage
example28 Program
BSD 3-Clause
7 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(color) :: c
Source Code
program example28
   use forimage, only: color
   implicit none
   type(color) :: c
   call c%set('red', use_library=.true.)
   call c%print()
end program example28
Call graph
example28 calls set
set calls set_by_name, set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_name, set_rgb, set_xyz
set_by_name calls initialize_colors
initialize_colors calls set, convert
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv, rgb_to_xyz, xyz_to_rgb