example29 – ForImage
example29 Program
BSD 3-Clause
7 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(color) :: c
Source Code
program example29
   use forimage, only: color
   implicit none
   type(color) :: c
   call c%print_available_colors()
   call c%save_available_colors()
end program example29
Call graph
example29 calls print_available_colors, save_available_colors
print_available_colors calls initialize_colors
save_available_colors calls initialize_colors
initialize_colors calls convert, set
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv, rgb_to_xyz, xyz_to_rgb
set calls set_by_name, set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_name, set_rgb, set_xyz
set_by_name calls initialize_colors