example19 – ForImage
example19 Program
14 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: ex19
integer, dimension(4,12) :: px
Source Code
program example19
    use forimage, only: format_pnm
    implicit none
    type(format_pnm) :: ex19
    integer, dimension(4,12) :: px
    px(1,:)  = [0,0,0,0,0,0,0,0,0,15,0,15]
    px(2,:)  = [0,0,0,0,15,7,0,0,0,0,0,0]
    px(3,:)  = [0,0,0,0,0,0,0,15,7,0,0,0]
    px(4,:)  = [15,0,15,0,0,0,0,0,0,0,0,0]
    call ex19%set_pnm(encoding='binary', file_format='ppm', width=4, height=4, max_color=15, comment='example 2', pixels=px)
    call ex19%swap_channels(swap='bg')
    call ex19%export_pnm('pnm_files/img6_binary_swap')
    call ex19%finalize()
end program example19
Call graph
example19 calls deallocate_pnm, export_pnm, set_pnm, swap_channels
export_pnm calls set_format
set_pnm calls allocate_pixels, set_file_format, set_format, set_header, set_pixels
swap_channels calls check_pixel_range
set_header calls set_comment, set_height, set_magicnumber, set_max_color, set_width
set_pixels calls check_pixel_range