example8 – ForImage
example8 Program
8 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: ex8
Source Code
program example8
    use forimage, only: format_pnm
    implicit none
    type(format_pnm) :: ex8
    call ex8%import_pnm('pnm_files/img2_ascii','pgm','ascii')
    call ex8%export_pnm('pnm_files/img2_ascii_ex')
    call ex8%finalize()
end program example8
Call graph
example8 calls deallocate_pnm, export_pnm, import_pnm
export_pnm calls set_format
import_pnm calls allocate_pixels, check_pixel_range, set_file_format, set_format, set_pixels
set_pixels calls check_pixel_range