example1 – ForImage
example1 Program
19 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: ex1
integer, dimension(10,6) :: px
Source Code
program example1
    use forimage, only: format_pnm
    implicit none
    type(format_pnm) :: ex1
    integer, dimension(10,6) :: px
    px(1,:)  = [0,0,0,0,1,0]
    px(2,:)  = [0,0,0,0,1,0]
    px(3,:)  = [0,0,0,0,1,0]
    px(4,:)  = [0,0,0,0,1,0]
    px(5,:)  = [0,0,0,0,1,0]
    px(6,:)  = [0,0,0,0,1,0]
    px(7,:)  = [1,0,0,0,1,0]
    px(8,:)  = [0,1,1,1,0,0]
    px(9,:)  = [0,0,0,0,0,0]
    px(10,:) = [0,0,0,0,0,0]
    call ex1%set_pnm(encoding='ascii', file_format='pbm', width=6, height=10, comment='example 1', pixels=px)
    call ex1%export_pnm('pnm_files/example1_ascii')
    call ex1%dlloc()
end program example1
Call graph
example1 calls deallocate_pnm, export_pnm, set_pnm
set_pnm calls allocate_pixels, set_file_format, set_format, set_header, set_pixels
set_header calls set_comment, set_height, set_magicnumber, set_max_color, set_width