example10 – ForImage
example10 Program
8 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: ex10
Source Code
program example10
    use forimage, only: format_pnm
    implicit none
    type(format_pnm) :: ex10
    call ex10%import_pnm('pnm_files/img4_binary','pbm','binary')
    call ex10%export_pnm('pnm_files/img4_binary_ex')
    call ex10%finalize()
end program example10
Call graph
example10 calls deallocate_pnm, export_pnm, import_pnm
export_pnm calls set_format
import_pnm calls allocate_pixels, check_pixel_range, set_file_format, set_format, set_pixels
set_pixels calls check_pixel_range