example20 – ForImage
example20 Program
14 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: ex20
integer, dimension(4,12) :: px
Source Code
program example20
    use forimage, only: format_pnm
    implicit none
    type(format_pnm) :: ex20
    integer, dimension(4,12) :: px
    px(1,:)  = [0,0,0,0,0,0,0,0,0,15,0,15]
    px(2,:)  = [0,0,0,0,15,7,0,0,0,0,0,0]
    px(3,:)  = [0,0,0,0,0,0,0,15,7,0,0,0]
    px(4,:)  = [15,0,15,0,0,0,0,0,0,0,0,0]
    call ex20%set_pnm(encoding='binary', file_format='ppm', width=4, height=4, max_color=15, comment='example 2', pixels=px)
    call ex20%remove_channels(remove_r=.true., remove_b=.true.)
    call ex20%export_pnm('pnm_files/img6_binary_remove')
    call ex20%finalize()
end program example20
Call graph
example20 calls deallocate_pnm, export_pnm, remove_channels, set_pnm
export_pnm calls set_format
remove_channels calls check_pixel_range
set_pnm calls allocate_pixels, set_file_format, set_format, set_header, set_pixels
set_header calls set_comment, set_height, set_magicnumber, set_max_color, set_width
set_pixels calls check_pixel_range