example6 – ForImage
example6 Program
13 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: ex6
integer, dimension(4,12) :: px
Source Code
program example6
    use forimage, only: format_pnm
    implicit none
    type(format_pnm) :: ex6
    integer, dimension(4,12) :: px
    px(1,:)  = [0,0,0,0,0,0,0,0,0,15,0,15]
    px(2,:)  = [0,0,0,0,15,7,0,0,0,0,0,0]
    px(3,:)  = [0,0,0,0,0,0,0,15,7,0,0,0]
    px(4,:)  = [15,0,15,0,0,0,0,0,0,0,0,0]
    call ex6%set_pnm(encoding='binary', file_format='ppm', width=4, height=4, max_color=15, comment='example 2', pixels=px)
    call ex6%export_pnm('pnm_files/example6_binary')
    call ex6%finalize()
end program example6
Call graph
example6 calls deallocate_pnm, export_pnm, set_pnm
export_pnm calls set_format
set_pnm calls allocate_pixels, set_file_format, set_format, set_header, set_pixels
set_header calls set_comment, set_height, set_magicnumber, set_max_color, set_width