example27 – ForImage
example27 Program
BSD 3-Clause
10 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(color) :: custom_color
type(color) :: nearest_color
Source Code
program example27
   use forimage, only: ik, color
   implicit none
   type(color) :: custom_color, nearest_color
   call custom_color%set(name='custom_color', decimal=16711680_ik)
   print'(a)', 'Find the nearest color to the custom color'
   call custom_color%convert('decimal2rgb')
   call custom_color%find_nearest(nearest_color)
   call nearest_color%print()
end program example27
Call graph
example27 calls convert, find_nearest, set
convert calls cmyk_to_rgb, decimal_to_rgb, hex_to_rgb, hsl_to_rgb, hsv_to_rgb, rgb_to_cmyk, rgb_to_decimal, rgb_to_hex, rgb_to_hsl, rgb_to_hsv, rgb_to_xyz, xyz_to_rgb
find_nearest calls get_rgb, initialize_colors
set calls set_by_name, set_cmyk, set_decimal, set_hex, set_hsl, set_hsv, set_name, set_rgb, set_xyz
initialize_colors calls convert, set
set_by_name calls initialize_colors