test20 – ForImage
test20 Program
BSD 3-Clause
18 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: image
integer(kind=ik), dimension(4,12) :: px
Source Code
program test20
    use forimage, only: format_pnm, ik
    implicit none
    type(format_pnm) :: image
    integer(ik), dimension(4,12) :: px
    print*,' '
    print'(a)', 'Test 20'
    px(1,:)  = [14,12,11,0,0,0,0,0,0,15,0,15]
    px(2,:)  = [0,0,0,0,15,7,0,0,0,0,0,0]
    px(3,:)  = [0,0,0,0,0,0,0,15,7,0,0,0]
    px(4,:)  = [15,0,15,0,0,0,0,0,0,0,0,0]
    call image%set_pnm(encoding='binary', file_format='ppm', width=4, height=4, max_color=15, comment='test 2', pixels=px)
    call image%remove_channels(remove_r=.true., remove_b=.true.)
    call image%export_pnm('pnm_files/img3_binary_remove')
    call image%export_pnm('pnm_files/img3_ascii_remove', 'ascii')
    call image%print_info()
    call image%finalize()
end program test20
Call graph
test20 calls deallocate_pnm, export_pnm, print_info, remove_channels, set_pnm
export_pnm calls encode_binary_pbm_pixels, set_format, write_header
print_info calls aspect_ratio, average_colors, pixel_size
remove_channels calls check_pixel_range
set_pnm calls set_pixels, allocate_pixels, set_file_format, set_format, set_header
set_header calls set_comment, set_height, set_magicnumber, set_max_color, set_width
set_pixel_a calls check_pixel_range