test10 – ForImage
test10 Program
BSD 3-Clause
11 statements
Source File
Uses
forimage
Calls
Variables
Type Attributes Name Initial
type(format_pnm) :: image
Source Code
program test10
    use forimage, only: format_pnm
    implicit none
    type(format_pnm) :: image
    print*,' '
    print'(a)', 'Test 10'
    call image%import_pnm('pnm_files/img1_binary','pbm','binary')
    ! Print the image information to the screen
    call image%print_info()
    call image%export_pnm('pnm_files/img1_binary_ex')
    call image%finalize()
end program test10
Call graph
test10 calls deallocate_pnm, export_pnm, import_pnm, print_info
export_pnm calls encode_binary_pbm_pixels, set_format, write_header
import_pnm calls allocate_pixels, check_pixel_range, decode_binary_pbm_pixels, read_header, set_file_format, set_format
print_info calls aspect_ratio, average_colors, pixel_size